"""add user_id in profiles

Revision ID: 083473de6de2
Revises: 6ea9f766f742
Create Date: 2023-11-07 23:43:22.969570

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "083473de6de2"
down_revision: Union[str, None] = "6ea9f766f742"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("userprofiles_user_id_key", "userprofiles", type_="unique")
    op.drop_constraint("userprofiles_user_id_fkey", "userprofiles", type_="foreignkey")
    op.create_foreign_key(
        None,
        "userprofiles",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userprofiles", type_="foreignkey")
    op.create_foreign_key(
        "userprofiles_user_id_fkey", "userprofiles", "users", ["user_id"], ["id"]
    )
    op.create_unique_constraint("userprofiles_user_id_key", "userprofiles", ["user_id"])
    # ### end Alembic commands ###
