"""add profile image

Revision ID: 66eeb9b9d4ff
Revises: cab4ed2bc27c
Create Date: 2023-11-05 21:20:01.132427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eeb9b9d4ff'
down_revision: Union[str, None] = 'cab4ed2bc27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profileimages',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('img', sa.String(length=128), nullable=False),
    sa.Column('minetype', sa.String(length=128), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['userprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profileimages')
    # ### end Alembic commands ###
