"""add default values

Revision ID: 1aae2ede1b99
Revises: fea7b981728d
Create Date: 2023-10-26 16:12:19.896688

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aae2ede1b99"
down_revision: Union[str, None] = "fea7b981728d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "tasks",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "projects",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
