"""update fk in projects

Revision ID: 02e8d210f1c3
Revises: 9683d41d0736
Create Date: 2023-11-09 16:09:27.736543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e8d210f1c3'
down_revision: Union[str, None] = '9683d41d0736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_team_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_creator_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_creator_id_fkey', 'projects', 'users', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('projects_team_id_fkey', 'projects', 'teams', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
