"""updte fk with CACSADE

Revision ID: 58ae23e83ba7
Revises: 24e662c57be5
Create Date: 2023-11-29 19:40:32.180697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ae23e83ba7'
down_revision: Union[str, None] = '24e662c57be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dialogs_interlocutor_id_fkey', 'dialogs', type_='foreignkey')
    op.drop_constraint('dialogs_creator_id_fkey', 'dialogs', type_='foreignkey')
    op.create_foreign_key(None, 'dialogs', 'users', ['interlocutor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dialogs', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'dialogs', type_='foreignkey')
    op.drop_constraint(None, 'dialogs', type_='foreignkey')
    op.create_foreign_key('dialogs_creator_id_fkey', 'dialogs', 'users', ['creator_id'], ['id'])
    op.create_foreign_key('dialogs_interlocutor_id_fkey', 'dialogs', 'users', ['interlocutor_id'], ['id'])
    # ### end Alembic commands ###
