"""remove profile table

Revision ID: 9683d41d0736
Revises: 94d0d83db26e
Create Date: 2023-11-08 17:32:05.860679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9683d41d0736'
down_revision: Union[str, None] = '94d0d83db26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_table('profiles',
    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profiles_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
    )
    # ### end Alembic commands ###
