"""update fk in associate tables

Revision ID: 039457afd4b0
Revises: 02e8d210f1c3
Create Date: 2023-11-09 16:14:45.328194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039457afd4b0'
down_revision: Union[str, None] = '02e8d210f1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_creator_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint('users_projects_user_id_fkey', 'users_projects', type_='foreignkey')
    op.drop_constraint('users_projects_project_id_fkey', 'users_projects', type_='foreignkey')
    op.create_foreign_key(None, 'users_projects', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'users_projects', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('users_tasks_user_id_fkey', 'users_tasks', type_='foreignkey')
    op.drop_constraint('users_tasks_task_id_fkey', 'users_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'users_tasks', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'users_tasks', 'tasks', ['task_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('users_teams_user_id_fkey', 'users_teams', type_='foreignkey')
    op.drop_constraint('users_teams_team_id_fkey', 'users_teams', type_='foreignkey')
    op.create_foreign_key(None, 'users_teams', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'users_teams', 'teams', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_teams', type_='foreignkey')
    op.drop_constraint(None, 'users_teams', type_='foreignkey')
    op.create_foreign_key('users_teams_team_id_fkey', 'users_teams', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('users_teams_user_id_fkey', 'users_teams', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_tasks', type_='foreignkey')
    op.drop_constraint(None, 'users_tasks', type_='foreignkey')
    op.create_foreign_key('users_tasks_task_id_fkey', 'users_tasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key('users_tasks_user_id_fkey', 'users_tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users_projects', type_='foreignkey')
    op.drop_constraint(None, 'users_projects', type_='foreignkey')
    op.create_foreign_key('users_projects_project_id_fkey', 'users_projects', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('users_projects_user_id_fkey', 'users_projects', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_creator_id_fkey', 'tasks', 'users', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
