"""rename project name to title

Revision ID: f42eb75854f5
Revises: 349077407852
Create Date: 2023-11-10 19:29:45.751624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42eb75854f5'
down_revision: Union[str, None] = '349077407852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.String(length=128), server_default=sa.text("CONCAT('New project ', substring(gen_random_uuid()::text, 1, 5))"), nullable=False))
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=128), server_default=sa.text('concat(\'New project \', "substring"((gen_random_uuid())::text, 1, 5))'), autoincrement=False, nullable=False))
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###
