"""edit user model

Revision ID: 5998ab48f00c
Revises: 1aae2ede1b99
Create Date: 2023-10-26 19:00:04.762984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5998ab48f00c'
down_revision: Union[str, None] = '1aae2ede1b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.drop_constraint('users_usename_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'usename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usename', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_usename_key', 'users', ['usename'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
