"""remove profileimages, add description to teams, add avatar_url to userprofiles

Revision ID: 6ea9f766f742
Revises: 66eeb9b9d4ff
Create Date: 2023-11-07 23:16:08.521482

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ea9f766f742"
down_revision: Union[str, None] = "66eeb9b9d4ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profileimages")
    op.add_column("teams", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "userprofiles", sa.Column("avatar_url", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userprofiles", "avatar_url")
    op.drop_column("teams", "description")
    op.create_table(
        "profileimages",
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("img", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "minetype", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column("profile_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["userprofiles.id"], name="profileimages_profile_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="profileimages_pkey"),
    )
    # ### end Alembic commands ###
